language: python
python:
- '3.6'
install:
- pip install -r requirements.txt --quiet
- pip install pytest
- pip install pytest-cov
- pip install coverage
- pip install mkdocs
- pip install mkdocs-material
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
- pytest tests --cov=autokeras
- sh docs.sh
after_script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
deploy:
- provider: pypi
  user: jhfjhfj1
  password:
    secure: U8U+CHDkQlCv6s0ZjbwAqW1RWxU8sV+EOeXVfCIOFJt9Igk16/Onoi8Bbdc52w3rPlgdtR78MxLgR6HsaVWSoZn0dardl6C/F3u+aGzh3dsQF2lfEH+Dl4Y+EasPmo4uKsH7rttT2kpn+w8zmL4IZz/W/ML1WkXv0Dhz6iH1uPS2dsC+uxdfz+W1iii/BACaPPzZdu79N+QBepRJs3VurXyB9UpV/FmsYSTB/2eP1yD/AzkV4RbhfSVRXDqIwvwpHOBqpY/4GJFONkC7oi7JtOMs/6ZjHw/2bpIziWPK1s7HbrYtqfs9w5RG279iwakU94O45xh2v73E++/oJtRqpFAGHAw0SNhm7dprSEU/EwJUaNKj2HGRmIQ2dvr56h3W1lsteS1GR9sNcHrR/AtA+sEiHDFUxlhALEVb9xI7Yk6Bl7/rpoqIBWKSyeu7LomGoCEs6ZE2ljPcRB8OIZSE7FzjiPpWfxabwPG84XufhR834z1C3qnepTkDDRYM/5M954lEbBp8eB8GJGj51DMNifXfHvtJosQPLChFrDrZlRYKLcvKuYASFeJc/v2+Q1p1vPyjHy1eMyM+bES57qBK1KbMVa+sY7dre26b0NMpcUpk6YczR7AIiD330ME7QHglJAHaacXUyBIfflRnPvmsAwB1HY0waH4/OvTFYMU+TLo=
  on:
    tags: true
    repo: jhfjhfj1/autokeras
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: docs/
  target-branch: gh-pages
  on:
    branch: master
env:
  global:
  - secure: fzJRkNh/KFGWot6O9CmhRUxD/b+4l30oydcrhptwggYk2EYWO7j13Cr3e/xO8QArkaFDMKuWGuwYROFvs0zwSCE/4JKb0WwdZvyZ8kVETkwt2J1scdntuBegIJIHss2SZEt3bWnr0VZTBtYbFELtBLNxVDrCLVNvwsa4KVQbIK6vzIlScHw4LQWEYN3bDzYZbHyVuxaX6E6uHaWwK63ALnExYToYJ/DHQ+RhOVLoBjNB+LMRqJkZvf9okdoq+wF7zRmTlJbkHuss2DlAdo8DhHu5CzugADRRvyd+/SBHRBu11fbw65CtDJ0AzTGu+i/sJ+6OVgT47Wyt3CgtROFCRQIRS2IWVS61Nd78G6obUT78eyEvHKCv1dfub8Qviw+mfi05+1u/mEiPyKjEXVO/Pu5Dfi7/qeefTTCneyFL/DvWw2puG33wlZoNY3dbltDIADVcaGH9YJF2JJNkaund3joz7gQAG9+F2BJVqsQe7ura4dJXY3dJhYkgzLh0jFSNH7Yx/BJoXNq1Zpcdm0TtvMumxGIBafTSV/s2B/sB+evrAff9nRdavpXLtS9IGGCx8cledGqMNwpNSBKnjVC0uGH3KPGlAGVv0o3EO7X2mZ/pAz9GQGAnlkZZRcYN3uXnTotJm8F+dro21k1diiNZxPCguInVjxg+EE3J/joVBog=
